{% set name = "jsonpickle" %}
{% set version = "3.0.2" %}
{% set sha256 = "e37abba4bfb3ca4a4647d28bb9f4706436f7b46c8a8333b4a718abafa8e46b37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.7
    - importlib_metadata

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jsonpickle

about:
  summary: Python library for serializing any arbitrary object graph into JSON. It can take almost any Python object and turn the object into JSON. Additionally, it can reconstitute the object back into Python.
  home: http://jsonpickle.github.io/
  dev_url: https://github.com/jsonpickle/jsonpickle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
    - synapticarbors
