schema_version: 1

context:
  name: jsonpickle
  version: 4.0.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f299818b39367c361b3f26bdba827d4249ab5d383cd93144d0f94b5417aacb35

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.2
    - setuptools_scm >=6.0
    - toml
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - jsonpickle
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python library for serializing any arbitrary object graph into JSON. It can take almost any Python object and turn the object into JSON. Additionally, it can reconstitute the object back into Python.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: http://jsonpickle.github.io/
  repository: https://github.com/jsonpickle/jsonpickle

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
    - synapticarbors
