context:
  name: jsonpickle
  version: 4.0.5
  python_min: "3.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: fc670852b204d77601b08f8f9333149ac37ab6d3fe4e6ed3b578427291f63736

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - setuptools >=61.2
    - setuptools_scm >=6.0
    - toml
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - jsonpickle
      pip_check: true
  - script:
      - python -c "import jsonpickle"
    requirements:
      run:
        - python ${{ python_min }}

about:
  summary: Python library for serializing any arbitrary object graph into JSON. It can take almost any Python object and turn the object into JSON. Additionally, it can reconstitute the object back into Python.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: http://jsonpickle.github.io/
  repository: https://github.com/jsonpickle/jsonpickle

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
    - synapticarbors
